// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"go_private_chain/internal/model"

	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	ITesDBCtx interface {
		Init(r *ghttp.Request, ctx *model.Context)
		Get(ctx context.Context) *model.Context
		SetTestDb(ctx context.Context, testDb *model.ContextGoTestDb)
	}
)

var (
	localTesDBCtx ITesDBCtx
)

func TesDBCtx() ITesDBCtx {
	if localTesDBCtx == nil {
		panic("implement not found for interface ITesDBCtx, forgot register?")
	}
	return localTesDBCtx
}

func RegisterTesDBCtx(i ITesDBCtx) {
	localTesDBCtx = i
}
