// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IGoTestDb interface {
		CreateJob(ctx context.Context, req string) error
	}
)

var (
	localGoTestDb IGoTestDb
)

func GoTestDb() IGoTestDb {
	if localGoTestDb == nil {
		panic("implement not found for interface IGoTestDb, forgot register?")
	}
	return localGoTestDb
}

func RegisterGoTestDb(i IGoTestDb) {
	localGoTestDb = i
}
